import { BsCameraVideo, BsBoxSeam, BsCamera, BsHeadphones, BsHeart } from "react-icons/bs";
import { FaLaptopCode } from "react-icons/fa";
import { RiMoneyDollarCircleLine } from "react-icons/ri";
import { AiOutlineDesktop, AiOutlineUser } from "react-icons/ai";
import { LuGraduationCap, LuPencil } from "react-icons/lu";
import { MdOutlineWorkOutline } from "react-icons/md";
export const sideBarDropdown =   [
    {
      id: "courses",
      title: "Courses",
      isCollapsible: true,
      isOpen: true,
      items: [
        {
          id: "development",
          title: "Development",
          icon: FaLaptopCode,
          isCollapsible: true,
          isOpen: true,
          items: [
            { id: "web", label: "Web development", count: 574, checked: false },
            { id: "data", label: "Data Science", count: 568, checked: false },
            { id: "mobile", label: "Mobile Development", count: 1345, checked: true },
            { id: "testing", label: "Software Testing", count: 317, checked: false },
            { id: "engineering", label: "Software Engineering", count: 31, checked: false },
            { id: "tools", label: "Software Development Tools", count: 558, checked: false },
            { id: "nocode", label: "No-Code Development", count: 37, checked: false },
          ],
        },
        {
          id: "business",
          title: "Business",
          icon: RiMoneyDollarCircleLine,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "finance",
          title: "Finance & Accounting",
          icon: RiMoneyDollarCircleLine,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "it",
          title: "IT & Software",
          icon: AiOutlineDesktop,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "office",
          title: "Office Productivity",
          icon: MdOutlineWorkOutline,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "personal",
          title: "Personal Development",
          icon: AiOutlineUser,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "design",
          title: "Design",
          icon: LuPencil,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "marketing",
          title: "Marketing",
          icon: LuGraduationCap,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "lifestyle",
          title: "Lifestyle",
          icon: BsBoxSeam,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "photography",
          title: "Photography & Video",
          icon: BsCamera,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "music",
          title: "Music",
          icon: BsHeadphones,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
        {
          id: "health",
          title: "Health & Fitness",
          icon: BsHeart,
          isCollapsible: true,
          isOpen: false,
          items: [],
        },
      ]
    },
    {
      id: "advancedFilters",
      title: "Advanced Filters",
      isCollapsible: true,
      isOpen: true,
      items: [
        { id: "html", label: "HTML 5", count: 1345, checked: false },
        { id: "css", label: "CSS 3", count: 12736, checked: false },
        { id: "react", label: "React", count: 1345, checked: false },
        { id: "webflow", label: "Webflow", count: 1345, checked: true },
        { id: "nodejs", label: "Node.js", count: 1345, checked: false },
        { id: "laravel", label: "Laravel", count: 1345, checked: false },
        { id: "saas", label: "Saas", count: 1345, checked: false },
        { id: "wordpress", label: "Wordpress", count: 1345, checked: false },
      ],
    },
    {
      id: "courseRating",
      title: "Course Rating",
      isCollapsible: true,
      isOpen: true,
      items: [
        { id: "5star", label: "5 Star", count: 1345, checked: false },
        { id: "4star", label: "4 Star & up", count: 1345, checked: false },
        { id: "3star", label: "3 Star & up", count: 1345, checked: true },
        { id: "2star", label: "2 Star & up", count: 1345, checked: false },
        { id: "1star", label: "1 Star & up", count: 1345, checked: false },
      ],
    },
    {
      id: "courseLevel",
      title: "Course Level",
      isCollapsible: true,
      isOpen: true,
      items: [
        { id: "all", label: "All Level", count: 1345, checked: false },
        { id: "beginner", label: "Beginner", count: 1345, checked: false },
        { id: "intermediate", label: "Intermediate", count: 1345, checked: false },
        { id: "expert", label: "Expert", count: 1345, checked: false },
      ],
    },
    {
      id: "courseDuration",
      title: "Course Duration",
      isCollapsible: true,
      isOpen: true,
      items: [
        { id: "days", label: "1 - 7 Days", count: 1345, checked: false },
        { id: "weeks", label: "1 - 4 Weeks", count: 1345, checked: false },
        { id: "months3", label: "1 - 3 Months", count: 1345, checked: true },
        { id: "months6", label: "3 - 6 Months", count: 1345, checked: false },
        { id: "months12", label: "6 - 12 Months", count: 1345, checked: false },
      ],
    },
  ]